substitutions:
  _REGION: me-west1
  _SERVICE: schedule-app-beta-api
  _REPOSITORY: schedule-app
  _IMAGE: schedule-app-api
  _TAG: manual

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - APP_ENV=staging,DATABASE_ENGINE=sqlite,SCHEDULE_APP_DATABASE_PATH=/tmp/schedule_app.db,PUBLIC_APP_BASE_URL=https://schedule-app-beta-api-eoewa4enxa-zf.a.run.app,SCHEDULE_APP_DEFAULT_API_BASE_URL=https://schedule-app-beta-api-eoewa4enxa-zf.a.run.app

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
